language: python
python:
- '2.7'
- '3.4'
install:
- pip install .
- pip install nose rednose spec
script:
- nosetests --with-doctest --with-specplugin
deploy:
    - provider: pypi
      distributions: sdist
      user: afriemann
      password:
        secure: "RF2LcP2C3NB7X7BiViPOSfVrQzmvz/GhztA17vv+qIJ8P7aDkn10gG+ClZTgu2kaigCMmyfbs3cIZntX33T09Cn6PriXb6VHIInmzdqVMR23s3SlaxW4iNOydj7hB99oH7AW3Ad/6OKnf5BQM7MmXW2VoPSB8bPhkKTlBqMqX7aX5h4C2UVp8BIwYK6IHCmeoNzo+HSYogPm0MC2EIlIfXszW1OYbmPAOf6Iu2LhHJUz7YIIRYQuxd/TBWcSEkm2YyXniEynZdSqqtnGib/WlCf+tMlycBidm8ZJZG+tKzKexj8sQUyY6n+NaGj/UrEjqs7GtqAyRfLlixxeBt3nb/XJ1kWbYQD/iIIbt1Q4CIS/Hg40pCSXLP+bpkibIuYzk0PIGbU1N+KMXPLgqHrEPFZXzTh1LnbmZTHdMJ4dGL80iuKghrnAiinj9+2gT4Ls3Wb9DCKi3CC5cwE7FCJbPQn0P8XBo3OPmqDxHa20c9kd0s5qW2GcDK7AvtMSJ371ENwNurJRfXiRuHZGM+K/Sbfl9XSRvYC//3/D0npcU53HcUkzCuzjOhegMghsOCBBSjHxV+/uUmRWvC6CEzHAiHTGKDIuEAcfBuqXZvLsw0ti4Jg1MmEpyu3/O5EJvFB+UYPHk6LNanQqbag39Ip+c18wFuf9NSAyvyseaVHUQHM="
      on:
        branch: master
        tags: true
        condition: $TRAVIS_PYTHON_VERSION = "3.4"
